export const LOCATION_REPOSITORY_TOKEN = Symbol('LOCATION_REPOSITORY_TOKEN');
export const LOCATION_READER_FACADE_TOKEN = Symbol('LOCATION_READER_FACADE_TOKEN');
export const LOCATION_FACADE_TOKEN = Symbol('LOCATION_FACADE_TOKEN');
