export const NPC_SESSION_REPOSITORY_TOKEN = Symbol('NPC_SESSION_REPOSITORY_TOKEN');
export const NPC_SESSION_READER_TOKEN = Symbol('NPC_SESSION_READER_TOKEN');
export const SPAWN_NPC_SESSION_USE_CASE_TOKEN = Symbol('SPAWN_NPC_SESSION_USE_CASE_TOKEN');
export const NPC_SESSION_FACADE_TOKEN = Symbol('NPC_SESSION_FACADE_TOKEN');
