export const CHARACTER_REPOSITORY_TOKEN = Symbol('CHARACTER_REPOSITORY_TOKEN');
export const CHARACTER_FACADE_TOKEN = Symbol('CHARACTER_FACADE_TOKEN');
export const FIND_USER_CHARACTERS_WITH_CLASS_USE_CASE_TOKEN = Symbol(
  'FIND_USER_CHARACTERS_WITH_CLASS_USE_CASE_TOKEN',
);
