export const CHARACTER_REPOSITORY_TOKEN = Symbol('CHARACTER_REPOSITORY_TOKEN');
export const CHARACTER_CLASS_READER_TOKEN = Symbol('CHARACTER_CLASS_READER_TOKEN');
export const CHARACTER_FACADE_TOKEN = Symbol('CHARACTER_FACADE_TOKEN');
