export const LOCATION_REPOSITORY_TOKEN = Symbol('LOCATION_REPOSITORY_TOKEN');
export const LOCATION_READER_TOKEN = Symbol('LOCATION_READER_FACADE_TOKEN');
export const BOOTSTRAP_LOCATIONS_USE_CASE_TOKEN = Symbol('BOOTSTRAP_LOCATIONS_TOKEN');
