export const QUEST_REPOSITORY_TOKEN = Symbol('QUEST_REPOSITORY_TOKEN');
export const QUEST_READER_TOKEN = Symbol('QUEST_READER_TOKEN');
export const PLAYER_QUEST_REPOSITORY_TOKEN = Symbol('PLAYER_QUEST_REPOSITORY_TOKEN');
export const PLAYER_QUEST_READER_TOKEN = Symbol('PLAYER_QUEST_READER_TOKEN');
export const QUEST_FACADE_TOKEN = Symbol('QUEST_FACADE_TOKEN');
