export const PLAYER_QUEST_REPOSITORY_TOKEN = Symbol('PLAYER_QUEST_REPOSITORY_TOKEN');
export const QUEST_REPOSITORY_TOKEN = Symbol('QUEST_REPOSITORY_TOKEN');
export const QUEST_FACADE_TOKEN = Symbol('QUEST_FACADE_TOKEN');
export const PLAYER_QUEST_FACADE_TOKEN = Symbol('PLAYER_QUEST_FACADE_TOKEN');
export const QUEST_READER_TOKEN = Symbol('QUEST_READER_TOKEN');
export const ACCEPT_QUEST_USE_CASE_TOKEN = Symbol('ACCEPT_QUEST_USE_CASE_TOKEN');
export const HANDLE_ENTITY_KILLED_USE_CASE_TOKEN = Symbol('HANDLE_ENTITY_KILLED_USE_CASE_TOKEN');
