export const MOB_SESSION_REPOSITORY_TOKEN = Symbol('MOB_SESSION_REPOSITORY_TOKEN');
export const GET_MOB_SESSION_SNAPSHOT_BY_ID_PORT = Symbol('GET_MOB_SESSION_SNAPSHOT_BY_ID_PORT');
export const MOB_SESSION_FACADE_TOKEN = Symbol('MOB_SESSION_FACADE_TOKEN');
