export const MOB_SESSION_REPOSITORY_TOKEN = Symbol('MOB_SESSION_REPOSITORY_TOKEN');
export const GET_MOB_SESSION_SNAPSHOT_BY_ID_PORT = Symbol('GET_MOB_SESSION_SNAPSHOT_BY_ID_PORT');
export const MOB_SESSION_FACADE_TOKEN = Symbol('MOB_SESSION_FACADE_TOKEN');
export const MOB_SESSION_READER_TOKEN = Symbol('MOB_SESSION_READER_TOKEN');
export const SPAWN_MOB_USE_CASE_TOKEN = Symbol('SPAWN_MOB_USE_CASE_TOKEN');
