export const INTERACTION_REPOSITORY_TOKEN = Symbol('interaction_repository_token');
export const INTERACTION_RESOLVER_SERVICE_TOKEN = Symbol('INTERACTION_RESOLVER_SERVICE_TOKEN');
export const REQUEST_TALK_TO_NPC_USE_CASE_TOKEN = Symbol('REQUEST_TALK_TO_NPC_USE_CASE_TOKEN');
export const REQUEST_USE_TELEPORT_USE_CASE_TOKEN = Symbol('REQUEST_USE_TELEPORT_USE_CASE_TOKEN');
export const PROCESS_INTERACTION_TICK_TOKEN = Symbol('PROCESS_INTERACTION_TICK_TOKEN');
