export const NPC_PERSISTENCE_REPOSITORY_TOKEN = Symbol('NPC_PERSISTENCE_REPOSITORY_TOKEN');
export const NPC_READER_TOKEN = Symbol('NPC_READER_TOKEN');
export const NPC_FACADE_TOKEN = Symbol('NPC_FACADE_TOKEN');
