export const BAG_CONTAINER_REPOSITORY_TOKEN = Symbol('BAG_CONTAINER_REPOSITORY_TOKEN');
export const EQUIPMENT_CONTAINER_REPOSITORY_TOKEN = Symbol('EQUIPMENT_CONTAINER_REPOSITORY_TOKEN');
export const EQUIPMENT_CONTAINER_FACADE_TOKEN = Symbol('EQUIPMENT_CONTAINER_FACADE_TOKEN');
export const CONTAINER_INITIALIZER_TOKEN = Symbol('CONTAINER_INITIALIZER_TOKEN');
