export const BAG_CONTAINER_REPOSITORY_TOKEN = Symbol('BAG_CONTAINER_REPOSITORY_TOKEN');
export const EQUIPMENT_CONTAINER_REPOSITORY_TOKEN = Symbol('EQUIPMENT_CONTAINER_REPOSITORY_TOKEN');
export const EQUIPMENT_CONTAINER_FACADE_TOKEN = Symbol('EQUIPMENT_CONTAINER_FACADE_TOKEN');
export const CONTAINER_INITIALIZER_TOKEN = Symbol('CONTAINER_INITIALIZER_TOKEN');
export const MOVE_ITEM_USE_CASE_TOKEN = Symbol('MOVE_ITEM_USE_CASE_TOKEN');
export const BAG_ITEM_MANAGEMENT_USE_CASE_TOKEN = Symbol('BAG_ITEM_MANAGEMENT_USE_CASE_TOKEN');
export const BAG_CONTAINER_READER_TOKEN = Symbol('BAG_CONTAINER_READER_TOKEN');
