export const CHANGE_PLAYER_LOCATION_USE_CASE_TOKEN = Symbol(
  'CHANGE_PLAYER_LOCATION_USE_CASE_TOKEN',
);
export const BUILD_LOCATION_WORLD_STATE_USE_CASE_TOKEN = Symbol(
  'BUILD_LOCATION_WORLD_STATE_USE_CASE_TOKEN',
);
export const REQUEST_MOVE_USE_CASE_TOKEN = Symbol('REQUEST_MOVE_USE_CASE_TOKEN');
export const REQUEST_ATTACK_USE_CASE_TOKEN = Symbol('REQUEST_ATTACK_USE_CASE_TOKEN');
export const REQUEST_USE_SKILL_USE_CASE_TOKEN = Symbol('REQUEST_USE_SKILL_USE_CASE_TOKEN');
export const REQUEST_ATTACK_CANCEL_USE_CASE_TOKEN = Symbol('REQUEST_ATTACK_CANCEL_USE_CASE_TOKEN');
export const REQUEST_USE_ITEM_USE_CASE_TOKEN = Symbol('REQUEST_USE_ITEM_USE_CASE_TOKEN');
export const MOVE_ITEM_USE_CASE_TOKEN = Symbol('MOVE_ITEM_USE_CASE_TOKEN');
export const MANAGE_BAG_USE_CASE_TOKEN = Symbol('MANAGE_BAG_ITEM_USE_CASE_TOKEN');

export const PROCESS_AI_TICK_USE_CASE_TOKEN = Symbol('PROCESS_AI_TICK_USE_CASE_TOKEN');

export const BUILD_INITIAL_WORLD_STATE_USE_CASE = Symbol('BUILD_INITIAL_WORLD_STATE_USE_CASE');
export const BUILD_PLAYER_LOCATION_STATE_USE_CASE_TOKEN = Symbol(
  'BUILD_PLAYER_LOCATION_STATE_USE_CASE_TOKEN',
);
