export const CHANGE_PLAYER_LOCATION_USE_CASE_TOKEN = Symbol(
  'CHANGE_PLAYER_LOCATION_USE_CASE_TOKEN',
);
export const BUILD_LOCATION_WORLD_STATE_USE_CASE_TOKEN = Symbol(
  'BUILD_LOCATION_WORLD_STATE_USE_CASE_TOKEN',
);
