export const ENTITY_SPAWN_REPOSITORY_TOKEN = Symbol('ENTITY_SPAWN_REPOSITORY_TOKEN');
export const SPAWN_READER_FACADE_TOKEN = Symbol('SPAWN_READER_FACADE_TOKEN');
export const SPAWN_FACADE_TOKEN = Symbol('SPAWN_FACADE_TOKEN');
