export const CHARACTER_CLASS_REPOSITORY = Symbol('CHARACTER_CLASS_REPOSITORY');
export const CHARACTER_CLASS_READER_TOKEN = Symbol('CHARACTER_CLASS_READER_TOKEN');
export const CHARACTER_CLASS_FACADE_TOKEN = Symbol('CHARACTER_CLASS_FACADE_TOKEN');
