export const ITEM_INSTANCE_REPOSITORY_TOKEN = Symbol('ITEM_INSTANCE_REPOSITORY_TOKEN');
export const ITEM_TEMPLATE_REPOSITORY_TOKEN = Symbol('ITEM_TEMPLATE_REPOSITORY_TOKEN');
export const ITEM_INSTANCE_FACADE_TOKEN = Symbol('ITEM_INSTANCE_FACADE_TOKEN');
export const ITEM_TEMPLATE_FACADE_TOKEN = Symbol('ITEM_TEMPLATE_FACADE_TOKEN');
