export const FACTION_REPOSITORY_TOKEN = Symbol('FACTION_REPOSITORY_TOKEN');
export const FACTION_FACADE_TOKEN = Symbol('FACTION_FACADE_TOKEN');
export const FACTION_READER_TOKEN = Symbol('FACTION_READER_TOKEN');
