export const IN_MEMORY_MOVEMENT_QUEUE_REPOSITORY = Symbol('IN_MEMORY_MOVEMENT_QUEUE_REPOSITORY');
export const MOVEMENT_QUEUE_FACADE_TOKEN = Symbol('MOVEMENT_QUEUE_FACADE_TOKEN');
export const PLAN_MOVEMENT_USE_CASE_TOKEN = Symbol('PLAN_MOVEMENT_USE_CASE_TOKEN');
