export const IN_MEMORY_MOVEMENT_QUEUE_REPOSITORY = Symbol('IN_MEMORY_MOVEMENT_QUEUE_REPOSITORY');
export const MOVEMENT_QUEUE_FACADE_TOKEN = Symbol('MOVEMENT_QUEUE_FACADE_TOKEN');
export const PLAN_MOVEMENT_USE_CASE_TOKEN = Symbol('PLAN_MOVEMENT_USE_CASE_TOKEN');
export const APPROACH_TARGET_SERVICE_TOKEN = Symbol('APPROACH_TARGET_SERVICE_TOKEN');
export const PROCESS_MOVEMENT_TICK_TOKEN = Symbol('PROCESS_MOVEMENT_TICK_TOKEN');
export const MOVEMENT_QUEUE_READER_TOKEN = Symbol('MOVEMENT_QUEUE_READER_TOKEN');
