export const PLAYER_SESSION_REPOSITORY = Symbol('IN_MEMORY_PLAYER_SESSION_REPOSITORY_TOKEN');
export const GET_PLAYER_SESSION_SNAPSHOT_BY_CHARACTER_ID_PORT = Symbol(
  'GET_PLAYER_SESSION_SNAPSHOT_BY_CHARACTER_ID_PORT',
);
