export const PLAYER_SESSION_REPOSITORY_TOKEN = Symbol('IN_MEMORY_PLAYER_SESSION_REPOSITORY_TOKEN');
export const GET_PLAYER_SESSION_SNAPSHOT_BY_CHARACTER_ID_TOKEN = Symbol(
  'GET_PLAYER_SESSION_SNAPSHOT_BY_CHARACTER_ID_TOKEN',
);
export const PLAYER_SESSION_FACADE_TOKEN = Symbol('PLAYER_SESSION_FACADE_TOKEN');
export const CONNECT_PLAYER_USE_CASE_TOKEN = Symbol('CONNECT_PLAYER_SESSION_TOKEN');
export const PLAYER_SESSION_READER_TOKEN = Symbol('PLAYER_SESSION_READER_TOKEN');
