export enum ServerToClientEvents {
  // TODO: rename to 'connection'
  PlayerConnected = 'player:connected',
  PlayerDisconnected = 'player:disconnected',
  PlayerWalk = 'player:walk',
  PlayerWalkBatch = 'player:walk-batch',
  PlayerResourcesBatch = 'player:resources-batch',
  PlayerStateUpdate = 'player:state-update',
  PlayerChangeLocation = 'player:change-location',
  PlayerAttack = 'player:attack',
  PlayerAttackStart = 'player:attack-start',
  PlayerSkillCooldownUpdate = 'player:skill-cooldown-update',
  PlayerJoined = 'player:joined',
  PlayerLeft = 'player:left',
  PlayerEntered = 'player:entered',
  PlayerUseTeleport = 'player:use-teleport',
  GameInitialState = 'game:initial-state',
  AoESpawn = 'aoe:spawn',
  AoERemove = 'aoe:remove',
  ChatWorld = 'chat:world',
  ChatLocation = 'chat:location',
  ChatDirect = 'chat:direct',
}

export enum ClientToServerEvents {
  PlayerWalk = 'player:walk',
  RequestUseTeleport = 'player:request-use-teleport',
  RequestAttackMove = 'player:request-attack-move',
  RequestUseSkill = 'player:request-use-skill',
  PlayerAttackCancelled = 'player:attack-cancelled',
  RequestInitialState = 'game:request-initial-state',
  PlayerSendWorldMessage = 'player:chat:world:send',
  PlayerSendLocationMessage = 'player:chat:location:send',
  PlayerSendDirectMessage = 'player:chat:direct:send',
}
