export enum ServerToClientEvents {
  // TODO: rename to 'connection'
  PlayerConnected = 'player:connected',
  PlayerDisconnected = 'player:disconnected',
  PlayerResourcesBatch = 'player:resources-batch',
  EntityStateUpdate = 'entity:state-update',
  PlayerChangeLocation = 'player:change-location',
  EntityAttackStart = 'entity:attack-start',
  PlayerSkillCooldownUpdate = 'player:skill-cooldown-update',
  PlayerJoined = 'player:joined',
  PlayerLeft = 'player:left',
  PlayerUseTeleport = 'player:use-teleport',
  GameInitialState = 'game:initial-state',
  MovementBatch = 'movement-batch',
  AoESpawn = 'aoe:spawn',
  AoERemove = 'aoe:remove',
  ChatWorld = 'chat:world',
  ChatLocation = 'chat:location',
  ChatDirect = 'chat:direct',
  PongTime = 'time:pong',
  RespawnMob = 'mob:respawn',
  BagAdd = 'bag:add',
}

export enum ClientToServerEvents {
  PlayerWalk = 'player:walk',
  RequestUseTeleport = 'player:request-use-teleport',
  RequestAttackMove = 'player:request-attack-move',
  RequestUseSkill = 'player:request-use-skill',
  PlayerAttackCancelled = 'player:attack-cancelled',
  RequestInitialState = 'game:request-initial-state',
  PlayerSendWorldMessage = 'player:chat:world:send',
  PlayerSendLocationMessage = 'player:chat:location:send',
  PlayerSendDirectMessage = 'player:chat:direct:send',
  PingTime = 'time:ping',
  BagAdd = 'bag:add',
}
